### ISSUE TITLE
Meeting today

### ISSUE THREAD

**Issue by Denoble** [sa7818/GDD#10]
Hi guys,
I am wondering when we have meeting today, is it still 3pm? . I will miss the class this morning but will make it to the meeting if it is still schedule for 3Pm

**Comment by lianboli** [comment]
Hi,

Today I have something to do at 3pm. I will arrive about 3:30.

BR
lianbo
2016-6-8 AM6:08，"Denoble" <notifications@github.com>写道：

**Comment by sa7818** [comment]
Hi all,
I also have another meeting. I can come library at 4.


On Wednesday, 8 June 2016, lianboli <notifications@github.com> wrote:

> Hi,
>
> Today I have something to do at 3pm. I will arrive about 3:30.
>
> BR
> lianbo
> 2016-6-8 AM6:08，"Denoble" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>写道：
>
> > Hi guys,
> > I am wondering when we have meeting today, is it still 3pm? . I will miss
> > the class this morning but will make it to the meeting if it is still
> > schedule for 3Pm
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/sa7818/GDD/issues/10>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ASxuo0bKQDmR5qdtVVJ-hmZ-ad66DJzgks5qJn-DgaJpZM4IwuL6
> >
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sa7818/GDD/issues/10#issuecomment-224549993>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOdUDN-2lFLNVG6dyhUPVRWXUXTJP2MZks5qJpiygaJpZM4IwuL6>
> .
>


-- 




Regards,
Sara.
