### ISSUE TITLE
Please do not  modify Makefile by youself

### ISSUE THREAD

**Issue by lianboli** [sa7818/GDD#15]
I notice that Sara update Makefile by herself. If you have problem with makefile, please comment or report bug to me. Each of us control one part of the project. If every one try to modify makefile, I could not control it. I am also not responsible to it.

Thanks

**Comment by sa7818** [comment]
Hello,

As I told you before,
I just add one same line for my tex file. Nothing else. There is no need to
send it to all.

On Saturday, 11 June 2016, lianboli <notifications@github.com> wrote:

> I notice that Sara update Makefile by herself. If you have problem with
> makefile, please comment or report bug to me. Each of us control one part
> of the project. If every one try to modify makefile, I could not control
> it. I am also not responsible to it.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sa7818/GDD/issues/15>, or mute the thread
> <https://github.com/notifications/unsubscribe/AOdUDMxUBfBONHpnrNX3zzUpzWkjJ7nTks5qKpeIgaJpZM4IzhzU>
> .
>


-- 




Regards,
Sara.

**Comment by sa7818** [comment]
For next time I will make an issue to inform you if I need to change the
Makefile.

Thanks.

On Saturday, 11 June 2016, lianboli <notifications@github.com> wrote:

> I notice that Sara update Makefile by herself. If you have problem with
> makefile, please comment or report bug to me. Each of us control one part
> of the project. If every one try to modify makefile, I could not control
> it. I am also not responsible to it.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sa7818/GDD/issues/15>, or mute the thread
> <https://github.com/notifications/unsubscribe/AOdUDMxUBfBONHpnrNX3zzUpzWkjJ7nTks5qKpeIgaJpZM4IzhzU>
> .
>


-- 




Regards,
Sara.

**Comment by lianboli** [comment]
Hello,

Yes, I see. But you can send me email about your change and I update the
makefile. When professor read our code and see there are two contributors
to makefile. Then which is my work? You can see each source file only has
one contributor.

Wish you could understand!

Thanks

**Comment by salaee** [comment]
Guys,

Since there are some undone tasks, Who can come to the university today to work on them together? Issues like this can only be done by talking and working together. Please respond here so that we can arrange the time and place.

@lianboli @sa7818 @Denoble @SharonQSY @tosicky @fd6713 

Thanks

**Comment by sa7818** [comment]
I am available after 4. I am working on another project with classmate. But
I am in the library by the way.

On Saturday, 11 June 2016, Sam Alaee <notifications@github.com> wrote:

> Guys,
>
> Since there are some undone tasks, Who can come to the university today to
> work on them together? Issues like this can only be done by talking and
> working together. Please respond here so that we can arrange the time and
> place.
>
> @lianboli <https://github.com/lianboli> @sa7818
> <https://github.com/sa7818> @Denoble <https://github.com/Denoble>
> @SharonQSY <https://github.com/SharonQSY> @tosicky
> <https://github.com/tosicky> @fd6713 <https://github.com/fd6713>
>
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sa7818/GDD/issues/15#issuecomment-225360619>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOdUDAw2241kjKAjn-xLmeQpUSFyd5Zyks5qKrOkgaJpZM4IzhzU>
> .
>


-- 




Regards,
Sara.

**Comment by sa7818** [comment]
It obviously shows that you did the most part. As Professor mentioned
everyone should contribute to Makfile. But you are right, you need to be
informed. For every change I will send you an Email, then you can change my
part in Makefile. Thats not a problem at all.

On Saturday, 11 June 2016, lianboli <notifications@github.com> wrote:

> Hello,
>
> Yes, I see. But you can send me email about your change and I update the
> makefile. When professor read our code and see there are two contributors
> to makefile. Then which is my work? You can see each source file only has
> one contributor.
>
> Wish you could understand!
>
> Thanks
>
>
> On Sat, Jun 11, 2016 at 10:02 AM, sa7818 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Hello,
> >
> > As I told you before,
> > I just add one same line for my tex file. Nothing else. There is no need
> to
> > send it to all.
> >
> > On Saturday, 11 June 2016, lianboli <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > I notice that Sara update Makefile by herself. If you have problem with
> > > makefile, please comment or report bug to me. Each of us control one
> part
> > > of the project. If every one try to modify makefile, I could not
> control
> > > it. I am also not responsible to it.
> > >
> > > Thanks
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/sa7818/GDD/issues/15>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AOdUDMxUBfBONHpnrNX3zzUpzWkjJ7nTks5qKpeIgaJpZM4IzhzU
> > >
> > > .
> > >
> >
> >
> > --
> >
> >
> >
> >
> > Regards,
> > Sara.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/sa7818/GDD/issues/15#issuecomment-225358326>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ASxuo9JsgFS5c5leYrI_Z-1AUZOBhP56ks5qKqrXgaJpZM4IzhzU
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sa7818/GDD/issues/15#issuecomment-225359880>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOdUDHNMPgkZmO1FVd1g226fuboCeQ-8ks5qKrC5gaJpZM4IzhzU>
> .
>


-- 




Regards,
Sara.

**Comment by lianboli** [comment]
Yes, that is what professor said. I also want to modify someone's code. But I just modify it on my own copy and test my code. It is not polite to update your own code to others code. That is the rule for cooperation.

**Comment by salaee** [comment]
@lianboli Can I meet you today?

**Comment by salaee** [comment]
Apparently there is no need to meet each other, if you could update the code and debug it, if not we will submit it the way it is now. 
There won't be any meetings for today or tomorrow. 
Have a good weekend.

**Comment by salaee** [comment]
To: @lianboli 
I have provided the documentations about each of these file (gdd.py, main.py, and download.py). By reading these documentations, you will get how these functions work and what we can expect from each of them as result. 
Please make the appropriate changes into the Makefile. I would have done it by now but since you said we should contact you. I'm writing this message here.

@SharonQSY  is now working on plot.py and hopefully it'll be done by tonight. @lianboli, you can make the appropriate changes in Makefile of her section too.

Thank you

**Comment by lianboli** [comment]
I read comments in download.py. I found that it only has station ID and
year information. For makefile, it must check target at specific path and
file name. So these information must passed to program. Program should not
make any assumption about file name and path name. Otherwise makefile will
try to download and plot each time.
If you insist on write path name and file name in program. Makefile could
not work.
