### ISSUE TITLE
The error of "Expected file path name or file-like object, got <class 'NoneType'> type"

### ISSUE THREAD

**Issue by SharonQSY** [sa7818/GDD#18]
Hi guys,
Does anyone meet this problem in Python?
And do you have any suggestions to fix this problem?

**Comment by fd6713** [comment]
You have to pass a valid file name to that function. The 'None' is being passed and the error says that you cannot use None for the file path.

**Comment by SharonQSY** [comment]
When I am passing the file name into the function, and When I try to print the data in the file. It can show data in the terminal. But, it also shows the error.I just did not get it, why it shows I am passing None.

**Comment by SharonQSY** [comment]
It worked. I indeed passing the filename of none type.
