### ISSUE TITLE
Project Steps

### ISSUE THREAD

**Issue by sa7818** [sa7818/GDD#2]
GDD Project
Steps:
1.Download Data and Extract that in three column, then put it in a new file.( Denoble-Tosin)
##### Consider three cities(for example: St John's- Alberta- Toronto)
2. Calculate GDD for selected data and store it in new file. (Sharon)
3. Create plot and display (Sharon)
4. Making directory structure for the whole project (Ghassem)
5. Prepare a latex report for what we have done (Sara)
6. Prepare web-presentation,  (Faramarz)
7. Command Line (Ghassem)

-  @SharonQSY @fd6713 @salaee @tosicky @lianboli @Denoble

**Comment by SharonQSY** [comment]
7. Plot the graph showing GDD,like https://mesonet.agron.iastate.edu/onsite/features/2015/05/150507.png (Sharon)
8.  Create makefile (Lianbo Li)

**Comment by lianboli** [comment]
Hi, Sharon,

You program plot should has file name 'ploy.py' and should be put into src
directory.

Best Regards
Lianbo

**Comment by SharonQSY** [comment]
Ok. 
I will change the plot directory, when I update  the new code of plotting. @lianboli
