### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by lianboli** [sa7818/GDD#21]
I just test the project with make. I found following problem:
download.py still does not work under current makefile. The program does not check the parameters 
plot.py still has hard-coded path and file name. I have passed the figure file's name and storage path by command line parameters. But the program ignore this. This will cause makefile could not find targets and plot these figures every time.
For modular design, program should not make any assumption about file name and storage position. All these info should be passed by command line parameters.

**Comment by salaee** [comment]
The problems you mentioned might be true in some sense. Those who wrote it should comment here. but I guess there has been some changes on how these functions should be since the first time we've met. I guess the better solution is change the Makefile according to the output of these files and how these functions work.

**Comment by fd6713** [comment]
@lianboli 
If you look at the download.py source code, there are only two arguments: stationid and year. We have're removed the city as the arguments. You have to change you code to be able to handle the latest version of download.py.
These changes are result of our group meetings in which you don't participate.

**Comment by lianboli** [comment]
Args:
stationid (int): this parameter is for the station id of a specific city
year (int): this parameter is for specifying a year for the data
Return:
string: this is a string value that defines the *.csv file that was
downloaded/stored.

This is the comments. I do not know how to check the string return from
your program. If you know how to check it, you can change the makefile.

Thanks
