### ISSUE TITLE
update Readme

### ISSUE THREAD

**Issue by SharonQSY** [sa7818/GDD#24]
Hi, @sa7818 
I add analyze_gdd.py in the src directory. I try to update Readme.md file. But File List(Directories) of csv_data/ 's background is grey, I cannot add analyza_gdd.py into this directory. I guess it may use latex to do it. So, could you help me add this file into makeme.md

Thank you, Sara

**Comment by sa7818** [comment]
Hi Sharon,

It s just a text file not latex. If you cant edit that, I will do that when
I get home.



On Monday, 13 June 2016, SharonQSY <notifications@github.com> wrote:

> Hi, @sa7818 <https://github.com/sa7818>
> I add analyze_gdd.py in the src directory. I try to update Readme.md file.
> But File List(Directories) of csv_data/ 's background is grey, I cannot add
> analyza_gdd.py into this directory. I guess it may use latex to do it. So,
> could you help me add this file into makeme.md
>
> Thank you, Sara
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sa7818/GDD/issues/24>, or mute the thread
> <https://github.com/notifications/unsubscribe/AOdUDPgfpRnqfX4Atr-JBXEbKETpr7S6ks5qLeTggaJpZM4I00xN>
> .
>


-- 




Regards,
Sara.

**Comment by SharonQSY** [comment]
Hi  @sa7818  Sara,
I got click edit button to modify the file. Sorry about that. I can modify Readme.md.

Thank you
Have a good night.
