### ISSUE TITLE
Where is the output folder

### ISSUE THREAD

**Issue by fd6713** [sa7818/GDD#25]
Why output directory is removed?

**Comment by sa7818** [comment]
I dont know, who remove that directory?

**Comment by salaee** [comment]
I don't know know deleted the directory but when there is no file in any directories, GitHub automatically deletes that directory or at least doesn't show it.

**Comment by fd6713** [comment]
But there were files in the output folder. 
Anyway, I'll create it again.

**Comment by SharonQSY** [comment]
That is what I am thinking about. Becuase all the images in the output directory were also been deleted.

**Comment by SharonQSY** [comment]
Do I need to upload the plot image into output directory?

**Comment by fd6713** [comment]
@SharonQSY 
I think we don't need the plot_images folder, I removed it.

**Comment by SharonQSY** [comment]
OK. i have a question about option task 1. When I try to plot 5-95 percentile, it shows like this. Is it possible? 
![figure_1](https://cloud.githubusercontent.com/assets/8648341/16057582/54487f7e-3255-11e6-9395-3ff77bdccbdf.png)
