### ISSUE TITLE
Makefile has been updated

### ISSUE THREAD

**Issue by lianboli** [sa7818/GDD#27]
Everything is ok currently. This is the log:

lilb@Ubuntu64-VirtualBox:~/courses/cmsc6950/project/GDD$ make clean
rm -rf ./csv_data/*
rm -rf ./output/*
rm *.png
rm *.pdf
lilb@Ubuntu64-VirtualBox:~/courses/cmsc6950/project/GDD$ make
echo "Download datafiles"
Download datafiles
python3.5 ./src/download.py 50089_2015.csv
Started downloading ...
Data for station with id 50089 for year 2015
Download completed...
Extracting required columns...
File saved.
echo "Download datafiles"
Download datafiles
python3.5 ./src/download.py 50089_2016.csv
Started downloading ...
Data for station with id 50089 for year 2016
Download completed...
Extracting required columns...
File saved.
echo "Download datafiles"
Download datafiles
python3.5 ./src/download.py 27211_2015.csv
Started downloading ...
Data for station with id 27211 for year 2015
Download completed...
Extracting required columns...
File saved.
echo "Download datafiles"
Download datafiles
python3.5 ./src/download.py 27211_2016.csv
Started downloading ...
Data for station with id 27211 for year 2016
Download completed...
Extracting required columns...
File saved.
echo "Download datafiles"
Download datafiles
python3.5 ./src/download.py 50430_2015.csv
Started downloading ...
Data for station with id 50430 for year 2015
Download completed...
Extracting required columns...
File saved.
echo "Download datafiles"
Download datafiles
python3.5 ./src/download.py 50430_2016.csv
Started downloading ...
Data for station with id 50430 for year 2016
Download completed...
Extracting required columns...
File saved.
echo "Calculate GDD"
Calculate GDD
python3.5 ./src/gdd.py ./csv_data/50089_2015.csv 10 30
~ Filename: ./csv_data/50089_2015.csv exists!
50089_2015.gdd is created.
echo "Calculate GDD"
Calculate GDD
python3.5 ./src/gdd.py ./csv_data/50089_2016.csv 10 30
~ Filename: ./csv_data/50089_2016.csv exists!
50089_2016.gdd is created.
echo "Calculate GDD"
Calculate GDD
python3.5 ./src/gdd.py ./csv_data/27211_2015.csv 10 30
~ Filename: ./csv_data/27211_2015.csv exists!
27211_2015.gdd is created.
echo "Calculate GDD"
Calculate GDD
python3.5 ./src/gdd.py ./csv_data/27211_2016.csv 10 30
~ Filename: ./csv_data/27211_2016.csv exists!
27211_2016.gdd is created.
echo "Calculate GDD"
Calculate GDD
python3.5 ./src/gdd.py ./csv_data/50430_2015.csv 10 30
~ Filename: ./csv_data/50430_2015.csv exists!
50430_2015.gdd is created.
echo "Calculate GDD"
Calculate GDD
python3.5 ./src/gdd.py ./csv_data/50430_2016.csv 10 30
~ Filename: ./csv_data/50430_2016.csv exists!
50430_2016.gdd is created.
echo "Plot temp graphs"
Plot temp graphs
python3.5 ./src/plot.py ./csv_data/50089_2015.csv
Plot min_max output file : ../output/50089_2015_minmax.png
echo "Plot temp graphs"
Plot temp graphs
python3.5 ./src/plot.py ./csv_data/50089_2016.csv
Plot min_max output file : ../output/50089_2016_minmax.png
echo "Plot temp graphs"
Plot temp graphs
python3.5 ./src/plot.py ./csv_data/27211_2015.csv
Plot min_max output file : ../output/27211_2015_minmax.png
echo "Plot temp graphs"
Plot temp graphs
python3.5 ./src/plot.py ./csv_data/27211_2016.csv
Plot min_max output file : ../output/27211_2016_minmax.png
echo "Plot temp graphs"
Plot temp graphs
python3.5 ./src/plot.py ./csv_data/50430_2015.csv
Plot min_max output file : ../output/50430_2015_minmax.png
echo "Plot temp graphs"
Plot temp graphs
python3.5 ./src/plot.py ./csv_data/50430_2016.csv
Plot min_max output file : ../output/50430_2016_minmax.png
python3.5 ./src/plot.py ./csv_data/50089_2015.gdd
Plot GDD output file : ../output/50089_2015_gdd.png
python3.5 ./src/plot.py ./csv_data/50089_2016.gdd
could not broadcast input array from shape (366) into shape (365)
python3.5 ./src/plot.py ./csv_data/27211_2015.gdd
Plot GDD output file : ../output/27211_2015_gdd.png
python3.5 ./src/plot.py ./csv_data/27211_2016.gdd
could not broadcast input array from shape (366) into shape (365)
python3.5 ./src/plot.py ./csv_data/50430_2015.gdd
Plot GDD output file : ../output/50430_2015_gdd.png
python3.5 ./src/plot.py ./csv_data/50430_2016.gdd
could not broadcast input array from shape (366) into shape (365)
python3.5 ./src/analyze_gdd.py ./csv_data/50089_2015.csv
mv analyze_gdd.png ./output/50089_2015_analyze_gdd.png
python3.5 ./src/analyze_gdd.py ./csv_data/50089_2016.csv
mv analyze_gdd.png ./output/50089_2016_analyze_gdd.png
python3.5 ./src/analyze_gdd.py ./csv_data/27211_2015.csv
mv analyze_gdd.png ./output/27211_2015_analyze_gdd.png
python3.5 ./src/analyze_gdd.py ./csv_data/27211_2016.csv
mv analyze_gdd.png ./output/27211_2016_analyze_gdd.png
python3.5 ./src/analyze_gdd.py ./csv_data/50430_2015.csv
mv analyze_gdd.png ./output/50430_2015_analyze_gdd.png
python3.5 ./src/analyze_gdd.py ./csv_data/50430_2016.csv
mv analyze_gdd.png ./output/50430_2016_analyze_gdd.png
echo "Bokeh!"
Bokeh!
python3.5 ./src/bokeh_html.py ./csv_data/50089_2015.csv
Generating min max bokeh file
echo "Bokeh!"
Bokeh!
python3.5 ./src/bokeh_html.py ./csv_data/50089_2016.csv
Generating min max bokeh file
echo "Bokeh!"
Bokeh!
python3.5 ./src/bokeh_html.py ./csv_data/27211_2015.csv
Generating min max bokeh file
echo "Bokeh!"
Bokeh!
python3.5 ./src/bokeh_html.py ./csv_data/27211_2016.csv
Generating min max bokeh file
echo "Bokeh!"
Bokeh!
python3.5 ./src/bokeh_html.py ./csv_data/50430_2015.csv
Generating min max bokeh file
echo "Bokeh!"
Bokeh!
python3.5 ./src/bokeh_html.py ./csv_data/50430_2016.csv
Generating min max bokeh file
echo "Generate report!"
Generate report!
pdflatex ./report/GDD.tex
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./report/GDD.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 2 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrartcl.cls
Document Class: scrartcl 2013/12/19 v3.12 KOMA-Script document class (article)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrkbase.sty
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrbase.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrlfile.sty
Package scrlfile, 2013/12/19 v3.12 KOMA-Script package (loading files)
                  Copyright (C) Markus Kohm

))) (/usr/share/texlive/texmf-dist/tex/latex/koma-script/tocbasic.sty)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrsize11pt.clo)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/typearea.sty
Package typearea, 2013/12/19 v3.12 KOMA-Script package (type area)
                  Copyright (C) Frank Neukam, 1992-1994
                  Copyright (C) Markus Kohm, 1994-

DIV calculation for typearea with good linewidth.

Package typearea Warning: Maybe no optimal type area settings!
(typearea)                The maximum limit of line width is about 29%
(typearea)                larger than the heuristically detected line width.
(typearea)                You may e.g. increase DIV, decrease fontsize
(typearea)                or change the papersize.

)) (/usr/share/texlive/texmf-dist/tex/latex/microtype/microtype.sty
(/usr/share/texlive/texmf-dist/tex/latex/microtype/microtype-pdftex.def)
(/usr/share/texlive/texmf-dist/tex/latex/microtype/microtype.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amscls/amsthm.sty)

! LaTeX Error: File `xcolor.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: report.pdf

! LaTeX Error: File `report.pdf' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: pdf)

Enter file name:

! LaTeX Error: Unknown option `svgnames' for package `xcolor'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.6 \usepackage
               [hang, small,labelfont=bf,up,textfont=it,up]{caption}
?
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/fix-cm.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/sectsty/sectsty.sty)

Class scrartcl Warning: Usage of package `fancyhdr' together
(scrartcl)              with a KOMA-Script class is not recommended.
(scrartcl)              I'd suggest to use
(scrartcl)              package `scrpage2' or `scrlayer-scrpage'.
(scrartcl)              Nevertheless, using requested
(scrartcl)              package `fancyhdr' on input line 12.

(/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/share/texlive/texmf-dist/tex/latex/lastpage/lastpage.sty)
(/usr/share/texlive/texmf-dist/tex/latex/lettrine/lettrine.sty
Loading lettrine.cfg
(/usr/share/texlive/texmf-dist/tex/latex/lettrine/lettrine.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/titling/titling.sty) (./GDD.aux)
(/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-cmr.cfg)
(/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty))
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
! Undefined control sequence.
\HorRule ->\color
                  {DarkGoldenrod} \rule {\linewidth }{1pt}
l.59 \maketitle

?
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1phv.fd)
! Undefined control sequence.
\@bspretitle ... \usefont {OT1}{phv}{b}{n} \color
                                                  {Black} \selectfont
l.59 \maketitle

?
! Undefined control sequence.
\@bspreauthor ...usefont {OT1}{phv}{b}{sl} \color
                                                  {DarkGreen}
l.59 \maketitle

?
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-msa.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd)
(/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-msb.cfg)
! Undefined control sequence.
\@bspostauthor ->\color
                        {Black} \\ \centering {Memorial University of Newfou...
l.59 \maketitle

?
! Undefined control sequence.
\@bspostauthor ...wfoundland}\\\centering {\color
                                                  {Blue}Instructor: Dr.James...
l.59 \maketitle

?
! Undefined control sequence.
\@bspostauthor ...tor: Dr.James Munroe} \titlepic
                                                  {\includegraphics [width=1...
l.59 \maketitle

?

LaTeX Warning: File `GDD.png' not found on input line 59.

! Package pdftex.def Error: File `GDD.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.59 \maketitle

?

LaTeX Font Warning: Font shape `OT1/cmtt/b/sl' undefined
(Font)              using `OT1/cmtt/m/n' instead on input line 59.

! Undefined control sequence.
\HorRule ->\color
                  {DarkGoldenrod} \rule {\linewidth }{1pt}
l.59 \maketitle

?

Overfull \hbox (75.15695pt too wide) in paragraph at lines 59--59
\OT1/cmr/m/n/10.95 (-20) DarkGoldenrod []
! Undefined control sequence.
<argument> \LettrineFont  \color
                                 {DarkGoldenrod} {\textsf {T}}
l.66 \initial{T}
                he Growing Degree Day, or GDD, is a heat unit that can be us...

?

Overfull \hbox (15.11984pt too wide) in paragraph at lines 66--67
[][]\OT1/cmr/m/n/10.95 (-20) he

Overfull \hbox (31.57253pt too wide) in paragraph at lines 66--67
\OT1/cmr/m/n/10.95 (-20) Grow-

Overfull \hbox (18.69685pt too wide) in paragraph at lines 66--67
\OT1/cmr/m/n/10.95 (-20) ing

Underfull \hbox (badness 2318) in paragraph at lines 66--67
\OT1/cmr/m/n/10.95 (+20) min-i-mum tem-per-a-tures to cal-cu-late GDD for

Underfull \hbox (badness 2617) in paragraph at lines 66--67
\OT1/cmr/m/n/10.95 (+20) three cities (St.John's, Cal-gary and Toronto)

Underfull \hbox (badness 1400) in paragraph at lines 66--67
\OT1/cmr/m/n/10.95 (+20) in one years. These steps can be found in

Underfull \hbox (badness 10000) in paragraph at lines 66--67
\OT1/cmr/m/n/10.95 (+20) http://github.come/sa7818/GDD in a pub-lic

Underfull \vbox (badness 10000) has occurred while \output is active
Underfull \hbox (badness 3209) in paragraph at lines 81--84
\OT1/cmr/m/n/10.95 (+20) To be-gin with,user needs to down-load daily

Underfull \hbox (badness 1314) in paragraph at lines 81--84
\OT1/cmr/m/n/10.95 (+20) his-tor-i-cal tem-per-a-ture data for three cities in

Underfull \hbox (badness 1888) in paragraph at lines 81--84
\OT1/cmr/m/n/10.95 (+20) Canada(St.John's, Cal-gary and Toronto) from
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
(/usr/share/texlive/texmf-dist/tex/latex/base/omscmr.fd)
Underfull \hbox (badness 1215) in paragraph at lines 101--102
[]\OT1/cmr/m/n/10.95 (+20) Creating plot show-ing an an-nual cy-cle of

LaTeX Warning: File `../output/plot_images/Calgary_2015.png' not found on input
 line 112.

! Package pdftex.def Error: File `../output/plot_images/Calgary_2015.png' not f
ound.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.112 ...]{../output/plot_images/Calgary_2015.png}

?

LaTeX Warning: File `../output/plot_images/Calgary_2016.png' not found on input
 line 118.

! Package pdftex.def Error: File `../output/plot_images/Calgary_2016.png' not f
ound.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.118 ...]{../output/plot_images/Calgary_2016.png}

?

LaTeX Warning: File `../output/plot_images/St.johns_2015.png' not found on inpu
t line 125.

! Package pdftex.def Error: File `../output/plot_images/St.johns_2015.png' not
found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.125 ...{../output/plot_images/St.johns_2015.png}

?

LaTeX Warning: File `../output/plot_images/Stjohns_2016.png' not found on input
 line 132.

! Package pdftex.def Error: File `../output/plot_images/Stjohns_2016.png' not f
ound.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.132 ...]{../output/plot_images/Stjohns_2016.png}

?

LaTeX Warning: `!h' float specifier changed to `!ht'.

LaTeX Warning: File `../output/plot_images/Toronto_2015.png' not found on input
 line 138.

! Package pdftex.def Error: File `../output/plot_images/Toronto_2015.png' not f
ound.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.138 ...]{../output/plot_images/Toronto_2015.png}

?

LaTeX Warning: `!h' float specifier changed to `!ht'.

LaTeX Warning: File `../output/plot_images/Toronto_2016.png' not found on input
 line 145.

! Package pdftex.def Error: File `../output/plot_images/Toronto_2016.png' not f
ound.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.145 ...]{../output/plot_images/Toronto_2016.png}

?

LaTeX Warning: `!h' float specifier changed to `!ht'.

[2]
AED: lastpage setting LastPage
[3] (./GDD.aux)

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

 ){/usr/share/texlive/texmf-dist/fonts/enc/dvips/base/8r.enc}</usr/share/texliv
e/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx10.pfb></usr/share/texlive/texm
f-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/share/texlive/texmf-dist
/fonts/type1/public/amsfonts/cm/cmmi8.pfb></usr/share/texlive/texmf-dist/fonts/
type1/public/amsfonts/cm/cmr10.pfb></usr/share/texlive/texmf-dist/fonts/type1/p
ublic/amsfonts/cm/cmr12.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/a
msfonts/cm/cmr17.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts
/cm/cmr9.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmss
17.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb
></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmti10.pfb></usr
/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmtt10.pfb></usr/share
/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmtt12.pfb></usr/share/texli
ve/texmf-dist/fonts/type1/urw/helvetic/uhvb8a.pfb></usr/share/texlive/texmf-dis
t/fonts/type1/urw/helvetic/uhvbo8a.pfb>
Output written on GDD.pdf (3 pages, 145915 bytes).
Transcript written on GDD.log.
make: *** [report.pdf] Error 1

**Comment by SharonQSY** [comment]
Thank you@lianboli.
👍👍
