### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by lianboli** [sa7818/GDD#28]
Plot.py has following bugs, plot.py has been changed after midnight by someone:
python3.5 ./src/plot.py ./csv_data/50430_2016.csv
Plot min_max output file : ../output/50430_2016_minmax.png
python3.5 ./src/plot.py ./csv_data/50089_2015.gdd
Plot GDD output file : ../output/50089_2015_gdd.png
python3.5 ./src/plot.py ./csv_data/50089_2016.gdd
Traceback (most recent call last):
  File "./src/plot.py", line 231, in <module>
    raise e
  File "./src/plot.py", line 221, in <module>
    plot_gdd(file_name, None, None)
  File "./src/plot.py", line 145, in plot_gdd
    avg_yrs[cnt] = accu_gdd_num
ValueError: could not broadcast input array from shape (366) into shape (365)
make: *** [50089_2016_gdd.png] Error 1

I try to download other station data. I change 50089 to other station ID. But why I could not download other stations' data?

**Comment by SharonQSY** [comment]
Now, this problem is because the data has leap year and non-leap year. So, the data with 365 items cannot add with 366 items.
I think there are two ways to solve it.
Frist, To remove month:2 day:29
second, to remove the year which year%4==0.
