### ISSUE TITLE
Project directory revision

### ISSUE THREAD

**Issue by salaee** [sa7818/GDD#3]
I believe we need to have the following directory structure:

/Readme.md
/Makefile

/src/
....../download.py
....../plot.py
....../gdd.py
....../main.py
....../testsuite.py
....../latex.tex

/csv_data/
.............../st_johns
.............../st_johns/2016.csv
.............../st_johns/2015.csv
.............../st_johns/{rest of the files}
.............../toronto
.............../alberta
.............../{name_of_the_city}

/outputs/
............/latex.pdf
............./plot_images/
................................./{all the images generated from ploting here}

/web/
......./{all the html files here}

@Denoble @SharonQSY @tosicky @sa7818 @lianboli @fd6713

**Comment by salaee** [comment]
I begin to feel that there is a confusion among team members about what are we expected to do in this project.
In the above issue, I explicitly defined a structure of files and folders for our project. If we don't follow a systematic directory structure, we cannot work with each other, because each of us, at some point, needs to continue someone else's work. That's why we need to put our files according to the above structure.
For example, Why are still *.py files in the root directory? and why in src directory none of the files are named as we talked about?
If you have a question regarding the efficiency of this directory structure, that's very good and I'm happy to hear your reasons and we can discuss about it, but if not, PLEASE, PLEASE, and I repeat it again, PLEASE FOLLOW THE ABOVE STRUCTURE.

WE DON'T HAVE TIME guys.

**Comment by SharonQSY** [comment]
Yup.
The reason I did not delete plot file and remove it into src/plot.py, the new data need to be clean before plot graph. So, I still working the code. As long as I finish the data, I will add the code in the right directory and delete old code. @salaee

**Comment by salaee** [comment]
Do you mean, if you want to use the csv files, you need to have your plot file in root?
I didn't get the why it has to be in root?
