### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by lianboli** [sa7818/GDD#8]
Hi, guys,

I wrote makefile and found following issues:
lilb@Ubuntu64-VirtualBox:~/courses/cmsc6950/project/GDD$ make
python3 ./src/datafromurl.py
Traceback (most recent call last):
  File "./src/datafromurl.py", line 4, in <module>
    f=open(var,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'STJOHNS1988TO1995.txt'
make: *** [Download] Error 1
lilb@Ubuntu64-VirtualBox:~/courses/cmsc6950/project/GDD$

Lianbo

**Comment by SharonQSY** [comment]
I think st johns 1988 to 1995 .txt has been removed. and it is not useful for our porject anymore,. Because we select the data from 2015 t0 2016.

**Comment by lianboli** [comment]
This error is caused by ./src/datafromurl.py. The data download program still is not ok.

**Comment by SharonQSY** [comment]
While, I just tried download the data, it works. I pull the directory into my system, and run .src/.csvlink.py file. It downloaded three cities and  two year's .cvs data file. So, I just think you may try .csvlink.py to download the data. @lianboli

**Comment by lianboli** [comment]
Hi, Sharon,
I just test your code. In csvlink.py, the directory "csv_data" CSV should be lower case. I change it and it work fine. Thank you. 
But, which code should I use now? I remember it is Denoble's job.
Lianbo

**Comment by SharonQSY** [comment]
Hi, Lianbo
which code do you want? You mean the code of plot graph? @lianboli
